-- Samuel Magana
-- smagan01@calpoly.edu

INSERT INTO Songs(SONGID, TITLE) VALUES (1, 'Overture');
INSERT INTO Songs(SONGID, TITLE) VALUES (2, 'A Bar In Amsterdam');
INSERT INTO Songs(SONGID, TITLE) VALUES (3, 'Demon Kitty Rag');
INSERT INTO Songs(SONGID, TITLE) VALUES (4, 'Tea With Cinnamon');
INSERT INTO Songs(SONGID, TITLE) VALUES (5, 'Hey Ho on the Devil''s Back');
INSERT INTO Songs(SONGID, TITLE) VALUES (6, 'Wading in Deeper');
INSERT INTO Songs(SONGID, TITLE) VALUES (7, 'Le Pop');
INSERT INTO Songs(SONGID, TITLE) VALUES (8, 'Der Kapitan');
INSERT INTO Songs(SONGID, TITLE) VALUES (9, 'Virginia Clemm');
INSERT INTO Songs(SONGID, TITLE) VALUES (10, 'Play My Darling  Play');
INSERT INTO Songs(SONGID, TITLE) VALUES (11, 'To the Sea');
INSERT INTO Songs(SONGID, TITLE) VALUES (12, 'Mother Superior');
INSERT INTO Songs(SONGID, TITLE) VALUES (13, 'Ain''t no Thang');
INSERT INTO Songs(SONGID, TITLE) VALUES (14, 'A Kiss Before You Go');
INSERT INTO Songs(SONGID, TITLE) VALUES (15, 'I Will Dance (When I Walk Away)');
INSERT INTO Songs(SONGID, TITLE) VALUES (16, 'Cherry Pie');
INSERT INTO Songs(SONGID, TITLE) VALUES (17, 'Land of Confusion');
INSERT INTO Songs(SONGID, TITLE) VALUES (18, 'Lady Marlene');
INSERT INTO Songs(SONGID, TITLE) VALUES (19, 'Rock-Paper-Scissors');
INSERT INTO Songs(SONGID, TITLE) VALUES (20, 'Cocktails and Ruby Slippers');
INSERT INTO Songs(SONGID, TITLE) VALUES (21, 'Soviet Trumpeter');
INSERT INTO Songs(SONGID, TITLE) VALUES (22, 'Loathsome M');
INSERT INTO Songs(SONGID, TITLE) VALUES (23, 'Shepherd''s Song');
INSERT INTO Songs(SONGID, TITLE) VALUES (24, 'Gypsy Flee');
INSERT INTO Songs(SONGID, TITLE) VALUES (25, 'God''s Great Dust Storm');
INSERT INTO Songs(SONGID, TITLE) VALUES (26, 'Ouch');
INSERT INTO Songs(SONGID, TITLE) VALUES (27, 'Listening to the World');
INSERT INTO Songs(SONGID, TITLE) VALUES (28, 'Johnny Blowtorch');
INSERT INTO Songs(SONGID, TITLE) VALUES (29, 'Flash');
INSERT INTO Songs(SONGID, TITLE) VALUES (30, 'Driving After You');
INSERT INTO Songs(SONGID, TITLE) VALUES (31, 'My Own Tune');
INSERT INTO Songs(SONGID, TITLE) VALUES (32, 'Badlands');
INSERT INTO Songs(SONGID, TITLE) VALUES (33, 'Old De Spain');
INSERT INTO Songs(SONGID, TITLE) VALUES (34, 'Oh My God');
INSERT INTO Songs(SONGID, TITLE) VALUES (35, 'Lady Gray');
INSERT INTO Songs(SONGID, TITLE) VALUES (36, 'Shine Like Neon Rays');
INSERT INTO Songs(SONGID, TITLE) VALUES (37, 'Flash in the Dark');
INSERT INTO Songs(SONGID, TITLE) VALUES (38, 'My Dear');
INSERT INTO Songs(SONGID, TITLE) VALUES (39, 'Bad Girl');
INSERT INTO Songs(SONGID, TITLE) VALUES (40, 'Rockland');
INSERT INTO Songs(SONGID, TITLE) VALUES (41, 'Curvaceous Needs');
INSERT INTO Songs(SONGID, TITLE) VALUES (42, 'Borka');
INSERT INTO Songs(SONGID, TITLE) VALUES (43, 'Let it Snow');
