-- Samuel Magana
-- smagan01@calpoly.edu

CREATE TABLE Campuses(
	ID INT NOT NULL,
	CAMPUS VARCHAR(60) NOT NULL, 
	LOCATION VARCHAR(30) NOT NULL, 
	COUNTY VARCHAR(30) NOT NULL, 
	YEAR INT NOT NULL, 
	Primary Key(ID)
);
	
CREATE TABLE CSUFees(
	CAMPUS INT NOT NULL,
	YEAR INT NOT NULL,
	CAMPUSFEE INT NOT NULL,
	FOREIGN KEY (CAMPUS) REFERENCES Campuses(ID)
	ON UPDATE CASCADE
	ON DELETE CASCADE
);

CREATE TABLE Degrees(
	YEAR INT NOT NULL,
	CAMPUS INT NOT NULL,
	DEGREES INT NOT NULL,
    FOREIGN KEY (CAMPUS) REFERENCES Campuses(ID)
	ON UPDATE CASCADE
	ON DELETE CASCADE
);

CREATE TABLE Disciplines(
	ID INT NOT NULL UNIQUE,
	NAME VARCHAR(100) NOT NULL
);

CREATE TABLE disEnroll(
	CAMPUS INT NOT NULL,
	DISCIPLINE INT NOT NULL,
	YEAR INT NOT NULL,
	UNDERGRADUATE INT NOT NULL,
	GRADUATE INT NOT NULL,
	FOREIGN KEY(CAMPUS) REFERENCES Campuses(ID)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	FOREIGN KEY(DISCIPLINE) REFERENCES Disciplines(ID)
	ON UPDATE CASCADE
	ON DELETE CASCADE
);

CREATE TABLE Enrollment(
	CAMPUS INT NOT NULL,
	YEAR INT NOT NULL,
	TOTALENROLLMENT_AY INT NOT NULL,
	FTE_AY INT NOT NULL,
	FOREIGN KEY(CAMPUS) REFERENCES Campuses(ID)
	ON UPDATE CASCADE
	ON DELETE CASCADE
);
CREATE TABLE Faculty(
    CAMPUS INT NOT NULL,
	YEAR INT NOT NULL,
	FACULTY DECIMAL(6,2) NOT NULL,
	FOREIGN KEY(CAMPUS) REFERENCES Campuses(ID)
	ON UPDATE CASCADE
	ON DELETE CASCADE
);

