CREATE TABLE Rooms(
    ROOMID VARCHAR(50) NOT NULL,
    ROOMNAME VARCHAR(50) NOT NULL,
    BEDS INT NOT NULL,
    BEDTYPE VARCHAR(50) NOT NULL,
    MAXOCCUPANCY INT NOT NULL,
    BASEPRICE INT NOT NULL,
    DECOR VARCHAR(50) NOT NULL,
    PRIMARY KEY (ROOMID)
);
CREATE TABLE Reservations(
    CODE INT NOT NULL,
    ROOM VARCHAR(50) NOT NULL,
    CHECKIN DATE NOT NULL,
    CHECKOUT DATE NOT NULL,
    RATE DOUBLE NOT NULL,
    LASTNAME VARCHAR(50) NOT NULL,
    FIRSTNAME VARCHAR(50) NOT NULL,
    ADULTS INT NOT NULL,
    KIDS INT NOT NULL,
    FOREIGN KEY(ROOM) REFERENCES Rooms(ROOMID)
);