CREATE TABLE Customers(
    ID INT NOT NULL,
    LASTNAME VARCHAR(50),
    FIRSTNAME VARCHAR(50),
    PRIMARY KEY(ID)
);
CREATE TABLE Receipts(
    RECIEPTNUMBER INT NOT NULL,
    DATES DATE NOT NULL,
    CUSTOMERID INT NOT NULL,
    PRIMARY KEY(RECIEPTNUMBER),
    FOREIGN KEY (CUSTOMERID) REFERENCES Customers(ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
CREATE TABLE Goods(
    ID VARCHAR(50) NOT NULL,
    FLAVOR VARCHAR(50) NOT NULL,
    FOOD VARCHAR(50) NOT NULL,
    PRICE DECIMAL(6,2) NOT NULL,
    PRIMARY KEY(ID)
);
CREATE TABLE Items(
    RECIEPT INT NOT NULL,
    ORDINAL INT NOT NULL,
    ITEM VARCHAR(50) NOT NULL,
    FOREIGN KEY (RECIEPT) REFERENCES Receipts(RECIEPTNUMBER)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (ITEM) REFERENCES Goods(ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);