CREATE TABLE teachers(
    LASTNAME VARCHAR(50) NOT NULL,
    FIRSTNAME VARCHAR(50) NOT NULL,
    CLASSROOM INT NOT NULL,
    PRIMARY KEY (CLASSROOM)
);
CREATE TABLE List(
    LASTNAME VARCHAR(50) NOT NULL,
    FIRSTNAME VARCHAR(50) NOT NULL,
    GRADE INT NOT NULL,
    CLASSROOM INT NOT NULL,
    FOREIGN KEY(CLASSROOM) REFERENCES teachers(CLASSROOM)
);