CREATE TABLE Grapes(
    ID INT NOT NULL,
    GRAPE VARCHAR(100) UNIQUE,
    COLOR VARCHAR(100),
    PRIMARY KEY(ID)
);
CREATE TABLE Appelations(
    NO INT NOT NULL,
    APPELATION VARCHAR(100) UNIQUE,
    COUNTY VARCHAR(100),
    STATE VARCHAR(100),
    AREA VARCHAR(100),
    ISAVA VARCHAR(100),
    PRIMARY KEY(NO)
);
CREATE TABLE Wine(
    NO INT NOT NULL,
    GRAPE VARCHAR(100),
    WINERY VARCHAR(100),
    APPELATION VARCHAR(100),
    NAME VARCHAR(100),
    YEAR INT,
    PRICE INT,
    SCORE INT,
    CASES INT,
    FOREIGN KEY (GRAPE) REFERENCES Grapes(GRAPE)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (APPELATION) REFERENCES Appelations(APPELATION)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
