INSERT INTO Grapes(ID, GRAPE, COLOR) VALUES (1, 'Barbera', 'Red');
INSERT INTO Grapes(ID, GRAPE, COLOR) VALUES (2, 'Cabernet Franc', 'Red');
INSERT INTO Grapes(ID, GRAPE, COLOR) VALUES (3, 'Cabernet Sauvingnon', 'Red');
INSERT INTO Grapes(ID, GRAPE, COLOR) VALUES (4, 'Chardonnay', 'White');
INSERT INTO Grapes(ID, GRAPE, COLOR) VALUES (5, 'Grenache', 'Red');
INSERT INTO Grapes(ID, GRAPE, COLOR) VALUES (6, 'Malbec', 'Red');
INSERT INTO Grapes(ID, GRAPE, COLOR) VALUES (7, 'Marsanne', 'White');
INSERT INTO Grapes(ID, GRAPE, COLOR) VALUES (8, 'Merlot', 'Red');
INSERT INTO Grapes(ID, GRAPE, COLOR) VALUES (9, 'Mourvedre', 'Red');
INSERT INTO Grapes(ID, GRAPE, COLOR) VALUES (10, 'Muscat', 'White');
INSERT INTO Grapes(ID, GRAPE, COLOR) VALUES (11, 'Petite Sirah', 'Red');
INSERT INTO Grapes(ID, GRAPE, COLOR) VALUES (12, 'Pinot Noir', 'Red');
INSERT INTO Grapes(ID, GRAPE, COLOR) VALUES (13, 'Riesling', 'White');
INSERT INTO Grapes(ID, GRAPE, COLOR) VALUES (14, 'Roussanne', 'White');
INSERT INTO Grapes(ID, GRAPE, COLOR) VALUES (15, 'Sangiovese', 'Red');
INSERT INTO Grapes(ID, GRAPE, COLOR) VALUES (16, 'Sauvignon Blanc', 'White');
INSERT INTO Grapes(ID, GRAPE, COLOR) VALUES (17, 'Syrah', 'Red');
INSERT INTO Grapes(ID, GRAPE, COLOR) VALUES (18, 'Tempranillo', 'Red');
INSERT INTO Grapes(ID, GRAPE, COLOR) VALUES (19, 'Viognier', 'White');
INSERT INTO Grapes(ID, GRAPE, COLOR) VALUES (20, 'Zinfandel', 'Red');
